version: "3"

services:

    influxdb:
        image: influxdb/influxdb:latest
        volumes:
        - ./influxdb:/var/lib/influxdb
        ports: 
        - 8083:8083

    grafana:
        image: grafana/grafana:latest
        volumes:
        - ./grafana:/var/lib/grafana
        ports: 
        - 3000:3000
        links:
        - influxdb
        
    fastapi:
        image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
        ports:
        - 8080:8080
        links:
        - influxdb
