version: "3"

services:

    influxdb:
        image: influxdb:latest
        volumes:
          - ./influxdb:/var/lib/influxdb
        ports:
          - "8083:8083"
          - "8086:8086"
        environment:
          - INFLUXDB_DB=csc
          - INFLUXDB_ADMIN_USER=root
          - INFLUXDB_ADMIN_PASSWORD=root

    grafana:
        image: grafana/grafana:latest
        volumes:
          - ./grafana:/var/lib/grafana
        ports:
          - 3000:3000
        links:
          - influxdb

    # fastapi:
    #     image: tiangolo/uvicorn-gunicorn-fastapi:python3.7
    #     ports:
    #       - 80:80
    #     links:
    #       - influxdb
    #     volumes:
    #       - ./app:/app
