version: "3"

services:

    influxdb:
        image: influxdb:latest
        volumes:
          - ./influxdb:/var/lib/influxdb
        ports:
          - "8083:8083"
          - "8086:8086"
        environment:
          - INFLUXDB_DB=csc
          - INFLUXDB_ADMIN_USER=root
          - INFLUXDB_ADMIN_PASSWORD=root
          - INFLUXDB_HTTP_AUTH_ENABLED=true

    chronograf:
      image: chronograf:latest
      environment:
        INFLUXDB_URL: http://influxdb:8086
      ports:
        - "8889:8888"
      links:
        - influxdb

    grafana:
        image: grafana/grafana:latest
        volumes:
          - ./grafana:/var/lib/grafana
        ports:
          - 3000:3000
        links:
          - influxdb

    forecast:
        build:
          context: .
          dockerfile: ./forecast/Dockerfile
        image: forecast:latest
        volumes:
          - ./forecast:/usr/src/app
        links:
          - fastapi

    fastapi:
        build:
          context: .
          dockerfile: ./app/Dockerfile
        image: fastapi:latest
        ports:
          - 80:80
        environment:
          - LOG_LEVEL=debug
        # Seems to not create multiple worker?
        command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload", "--port", "80"]
        links:
          - influxdb
        volumes:
          - ./app:/app
